### ISSUE TITLE
HOLDの処理がおかしい

### ISSUE THREAD

**Issue by mizucoffee** [kb10uy/Seaurchin#15]
## 概要
HOLDの処理がおかしい

## 例
下記リンク先の譜面の17小節目（#016xx）のロングが片方しか認識していない
https://gist.github.com/kb10uy/20bb4f65d26b937776ff61eb2bd26755

## 環境

- Seaurchin v0.44.0
- Arch Linux

注: 推奨動作環境でないLinuxですが解析に影響は無いと思います...

**Comment by KawakawaRitsuki** [comment]
すみません、検証したのに追記するの忘れてました。

識別番号をバラにすると正常に動作したので、その辺だと思います（大雑把）
