### ISSUE TITLE
ひょっとしてチャンネル識別子26個じゃ足りなくない？

### ISSUE THREAD

**Issue by kb10uy** [kb10uy/Seaurchin#29]
いや僕も足りるだろとか思ってたんだけど、本家がそれじゃ足りないような譜面出してきてるし創作勢各位の動きを見ているとやっぱりもっと使えたほうが良いのではないか

なお [askyharkratta/ahk-format](https://github.com/askyharkraata/ahk-format) ではそもそも番号付けしないのでこの問題は発生しえない

**Comment by amenoshita-429** [comment]
既存譜面との互換性を考えると、ロングノーツ定義を
#mmmtlx+
mmm : 小節番号(10進 3桁)
t : レーン種別 (1-5)
l : レーン番号 (16進 1桁)
x+ : 識別番号 (半角英数1文字以上)
に変更するとかでしょうか

**Comment by kb10uy** [comment]
データ定義部分の互換性は双方に確保したいので、0.50.0リリースまでの Sus 2.x ではそこを拡張するのはやめておこうと考えてます。
拡張された番号などの仕様については Sus 3.x で対応するとして、現時点では小節番号の拡張との一貫性の観点から `#CHANNELBS` ディレクティブを用意してオフセット量を指定させる仕様にしたい所存です
