### ISSUE TITLE
SkillIndicators::SetCallbackを必ず呼ばないとSeaurchinが落ちる問題

### ISSUE THREAD

**Issue by amenoshita-429** [kb10uy/Seaurchin#32]
ScenePlayerに対し必ず
ScenePlayer@ player = ScenePlayer();
SetPlayerResources(skin, player);
player.Initialize();
player.GetCharacterInstance().GetSkillIndicators().SetCallback(SkillCallback(OnSkill));
のような形でコールバックを登録しておかないと譜面再生時にSeaurchinが落ちます。
コールバックの設定を義務付けるのであればそれはそれで構わないのですが、現状ではどこにもその旨が記載されておらず、バグかどうかの判断が付きません。
なお、落ちる原因は登録されたコールバックを呼ぶ際にnullチェックが行われないためのようです。

**Comment by kb10uy** [comment]
nullチェック落ちはバグですね、修正します
