### ISSUE TITLE
Scene(ScriptScene)がDisappearを呼んでも消えない

### ISSUE THREAD

**Issue by amenoshita-429** [kb10uy/Seaurchin#37]
https://github.com/kb10uy/Seaurchin/blob/849b6e10374298b146fa613ae4bc6d41251fd3bd/Seaurchin/ScriptScene.cpp#L86

実装としては消えなくて当然なんですけど、この実装である必要性はあるのでしょうか?
CoroutineSceneはフラグ管理を行っていますが……

**Comment by kb10uy** [comment]
(Scriptじゃない)Sceneからのコピペミスっぽいですね……
