### ISSUE TITLE
I can't Change resolution of Seaurchin

### ISSUE THREAD

**Issue by phj8189** [kb10uy/Seaurchin#46]
I using 1366x768 monitor, but if enable Seaurchin's Fullscreen, It being forced 1920x1080. How can I Change resolution of Fullscreen mode?

**Comment by mizucoffee** [comment]
Seaurchin is supported only 1280x720.
https://github.com/kb10uy/Seaurchin/blob/f389520b8e068ee709bb9af016f56e37300d661c/Seaurchin/Config.h#L37-L38
User can not change resolution.
The behavior is by design for skins.

**Comment by amenoshita-429** [comment]
求めてる挙動になるかはわかりかねますが、
https://dxlib.xsrv.jp/cgi/patiobbs/patio.cgi?mode=past&no=1310
この辺を参考に自前で裏画面を画面サイズに合わせて引き延ばして(あるいは縮小して)描画すれば改善するだろうとは思います。
それよりも気になるのは、なぜフルスクリーンを有効にした際に1920x1080という解像度が指定されるのかという点ですね。
DxLibの詳細な挙動まで確認していませんが、現在の実装ではフルスクリーン有効時は1280x720の裏画面がディスプレイサイズに引き延ばされるものだと思っています。
再度ディスプレイの設定を確認するとともに、どのような画面になっているかを教えていただきたいです。

To @phj8189 
What I wonder if is why the resolution of 1920x1080 is used when enabling full screen mode in your environment.
In the current implementation, I think that the back screen of 1280x720 will be stretched to the display size when full screen mode enable.
I would like you to check your display settings carefully.
Then, please let me know in the image what you see on your display.

**Comment by phj8189** [comment]
I checked it and problem resolved. thanks your help
