### ISSUE TITLE
CIでビルド

### ISSUE THREAD

**Issue by rinsuki** [kb10uy/Seaurchin#5]
AppVeyorとかよさそう
AppVeyorはビルドしたバイナリも配れる([例](https://ci.appveyor.com/project/Petitsurume/mastodon-bouyomichan/build/artifacts))

**Comment by mizucoffee** [comment]
まだ色々と調べている所ですが、少し前に発表されたAzure Pipelineも良さそうです。
OSSであれば **10個の並列ジョブ** が無料だったり、.NETのビルド/テストに対応していたり。
デプロイもできそうです。
