### ISSUE TITLE
ざっくばらんなバグ共

### ISSUE THREAD

**Issue by kb10uy** [kb10uy/Seaurchin#6]
たてた

**Comment by kb10uy** [comment]
BOMチェックの3バイト目が町がってる from hnakai

**Comment by kb10uy** [comment]
eb93472a0714f37ba201148f4728f3c5f8617239 で直した

**Comment by kb10uy** [comment]
前カウントの回数が不安
なんで？

**Comment by kb10uy** [comment]
89774080a01cda3c257db5d4eb7416212ecaadd1 で修正
判定順のせいだったっぽい

**Comment by bluish-elvis** [comment]
オートガードっぽいスキルやろうと思ってAbility OnStart内でresult.BoostGaugeByValue(int);やるとすぐ増えた分のゲージがもとに戻ってしまう

**Comment by kb10uy** [comment]
ノーツ数カウント時にリセットするやついらなそうですね、消しましょう
